import { describe, it, expect } from "vitest";
import { extractPubPackages, isPubFile, scanPubContent } from "../pub-scanner.js";
import type { FeedIOC } from "../threat-intel.js";
import { performanceBudget } from "./performance-budget.js";

const FEED: FeedIOC[] = [
  { type: "package", value: "pub:evil_pkg", severity: "critical", confidence: 0.9, family: "TestFamily" },
  { type: "package", value: "pub:hijacked_pkg@0.1.5", severity: "critical", confidence: 1.0 },
];

const hits = (content: string, file: string, feed: FeedIOC[] = FEED) =>
  scanPubContent(content, file, feed).filter((f) => f.rule === "PUB_MALICIOUS_PACKAGE");

const names = (content: string, file: string) =>
  extractPubPackages(content, file).map((p) => `${p.name}@${p.version ?? "-"}`);

const LOCK = `# Generated by pub
# See https://dart.dev/tools/pub/glossary#lockfile
packages:
  hijacked_pkg:
    dependency: "direct main"
    description:
      name: hijacked_pkg
      sha256: "0000000000000000000000000000000000000000000000000000000000000000"
      url: "https://pub.dev"
    source: hosted
    version: "0.1.5"
  evil_pkg:
    dependency: transitive
    description:
      name: evil_pkg
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.0"
  private_pkg:
    dependency: "direct main"
    description:
      name: evil_pkg
      url: "https://pub.internal.example"
    source: hosted
    version: "1.0.0"
  git_pkg:
    dependency: "direct main"
    description:
      path: "."
      ref: main
      url: "https://github.com/example/evil_pkg.git"
    source: git
    version: "1.0.0"
  flutter:
    dependency: "direct main"
    description: flutter
    source: sdk
    version: "0.0.0"
sdks:
  dart: ">=3.0.0 <4.0.0"
`;

describe("isPubFile", () => {
  it("accepts pubspec.lock and pubspec.yaml, nothing else", () => {
    expect(isPubFile("pubspec.lock")).toBe(true);
    expect(isPubFile("app/pubspec.yaml")).toBe(true);
    expect(isPubFile("pubspec.yml")).toBe(false);
    expect(isPubFile("analysis_options.yaml")).toBe(false);
  });
});

describe("extractPubPackages", () => {
  // A package served by another host is a different registry's package that
  // merely shares the name; git, path and sdk sources have no pub identity.
  it("reads only pub.dev-hosted lockfile packages, with exact versions and the real name", () => {
    expect(names(LOCK, "pubspec.lock")).toEqual(["hijacked_pkg@0.1.5", "evil_pkg@1.0.0"]);
  });

  // The map key is only a label; pub downloads description.name. A lockfile is
  // target-controlled, so an innocent-looking key must not hide the real name.
  it("uses description.name, not the lockfile map key", () => {
    const aliased = [
      "packages:",
      "  innocent_pkg:",
      '    dependency: "direct main"',
      "    description:",
      "      name: hijacked_pkg",
      '      url: "https://pub.dev"',
      "    source: hosted",
      '    version: "0.1.5"',
    ].join("\n");
    expect(names(aliased, "pubspec.lock")).toEqual(["hijacked_pkg@0.1.5"]);
  });

  // Same evasion one level up: a stray entry-level `name:` field placed before
  // the description. pub ignores it; only description.name is the identity.
  it("ignores a decoy name field outside the description", () => {
    const decoy = [
      "packages:",
      "  innocent_pkg:",
      "    name: innocent_pkg",
      '    url: "https://pub.dev"',
      "    description:",
      "      name: hijacked_pkg",
      '      url: "https://pub.dev"',
      "    source: hosted",
      '    version: "0.1.5"',
    ].join("\n");
    expect(names(decoy, "pubspec.lock")).toEqual(["hijacked_pkg@0.1.5"]);
  });

  it("reads pubspec.yaml dependencies, keeping only exact pins as versions", () => {
    const yaml = [
      "name: my_app",
      "environment:",
      '  sdk: ">=3.0.0 <4.0.0"',
      "  flutter: 3.22.0",
      "dependencies:",
      "  flutter:",
      "    sdk: flutter",
      "  hijacked_pkg: 0.1.5",
      "  evil_pkg: ^1.0.0",
      "  hosted_pkg:",
      "    hosted: https://pub.dev",
      "    version: '2.0.0'",
      "  private_pkg:",
      "    hosted: https://pub.internal.example",
      "    version: 1.0.0",
      "  git_pkg:",
      "    git: https://github.com/example/git_pkg.git",
      "dev_dependencies:",
      '  test_pkg: "1.2.3"',
      "dependency_overrides:",
      "  override_pkg: 3.0.0",
      "flutter:",
      "  uses-material-design: true",
    ].join("\n");
    expect(names(yaml, "pubspec.yaml")).toEqual([
      "hijacked_pkg@0.1.5",
      "evil_pkg@-",
      "hosted_pkg@2.0.0",
      "test_pkg@1.2.3",
      "override_pkg@3.0.0",
    ]);
  });
});

describe("extractPubPackages: flow maps and mirrors", () => {
  // The one-line flow map is the same dependency as the block form: path, git
  // and sdk sources have no pub identity, whatever their key is called.
  it("skips path, git and sdk dependencies written as flow maps", () => {
    const yaml = [
      "dependencies:",
      "  evil_pkg: {path: ../evil_pkg}",
      "  hijacked_pkg: { git: https://github.com/example/hijacked_pkg.git }",
      "  flutter: {sdk: flutter}",
      "  nested_git: {git: {url: https://github.com/example/x.git, ref: main}}",
      "  http: ^1.2.0",
    ].join("\n");
    expect(names(yaml, "pubspec.yaml")).toEqual(["http@-"]);
    expect(hits(yaml, "pubspec.yaml")).toEqual([]);
  });

  // The same flow maps continued over several lines.
  it("reads flow maps that span lines, with the same rules", () => {
    const yaml = [
      "dependencies:",
      "  evil_pkg: {",
      "    path: ../evil_pkg",
      "  }",
      "  hijacked_pkg: {hosted: https://pub.dev,",
      "    version: 0.1.5}",
      "  private_pkg: {",
      "    hosted: https://pub.internal.example,",
      "    version: 1.0.0,",
      "  }",
      "  http: ^1.2.0",
    ].join("\n");
    expect(names(yaml, "pubspec.yaml")).toEqual(["hijacked_pkg@0.1.5", "http@-"]);
  });

  it("reads a multi-line flow map closed by a bare brace, by `},`, or not at all", () => {
    const yaml = [
      "dependencies:",
      "  bare_close: {",
      "    hosted: {url: https://pub.dev},",
      "    version: 0.1.5",
      "  }",
      "  comma_close: {hosted: https://pub.dev,",
      "    version: 0.2.0},",
      "  never_closed: {hosted: https://pub.dev,",
      "    version: 0.3.0",
      "  http: ^1.2.0",
    ].join("\n");
    expect(names(yaml, "pubspec.yaml")).toEqual(["bare_close@0.1.5", "comma_close@0.2.0", "never_closed@0.3.0", "http@-"]);
  });

  it("reads nested hosted maps over several lines, section flow maps, quoted keys and anchors", () => {
    expect(names([
      "dependencies:",
      "  nested_hosted: {hosted: {",
      "      url: https://pub.dev},",
      "    version: 0.1.5}",
    ].join("\n"), "pubspec.yaml")).toEqual(["nested_hosted@0.1.5"]);
    expect(names("dependencies: {section_flow: 0.1.5, local: {path: ../x}}\n", "pubspec.yaml")).toEqual(["section_flow@0.1.5"]);
    expect(names('"dependencies":\n  "quoted_key": 0.1.5\n', "pubspec.yaml")).toEqual(["quoted_key@0.1.5"]);
    expect(names("dependencies:\n  anchored: &v 0.1.5\n", "pubspec.yaml")).toEqual(["anchored@0.1.5"]);
    // A hosted value that names no readable URL counts as pub.dev.
    expect(names("dependencies:\n  garbled: {hosted: {, version: 0.1.5}\n", "pubspec.yaml")).toEqual(["garbled@0.1.5"]);
    // A git dependency, and a private host, are not pub.dev packages.
    expect(names([
      "dependencies:",
      "  from_git: {",
      "    version: 0.1.5, git: {url: x}}",
      "  private_pkg: {hosted: {url: https://pub.internal.example}, version: 1.0.0}",
    ].join("\n"), "pubspec.yaml")).toEqual([]);
  });

  it("reads a long flow-form section, an anchor on a map, and pub.dev however it is spelled", () => {
    const many = Array.from({ length: 70 }, (_, i) => `  pkg_${i}: ^1.0.0,`);
    expect(names(["dependencies: {", ...many, "  late_pin: 0.1.5}"].join("\n"), "pubspec.yaml")).toContain("late_pin@0.1.5");
    expect(names("dependencies:\n  anchored_map: &m\n    version: 0.1.5\n", "pubspec.yaml")).toEqual(["anchored_map@0.1.5"]);
    expect(names("dependencies:\n  upper: {hosted: https://PUB.DEV, version: 0.1.5}\n", "pubspec.yaml")).toEqual(["upper@0.1.5"]);
    expect(names("dependencies:\n  port: {hosted: 'https://pub.dev:443/', version: 0.1.5}\n", "pubspec.yaml")).toEqual(["port@0.1.5"]);
  });

  it("reads pub.dev over http or with a trailing dot, and survives a huge nested flow map", () => {
    expect(names("dependencies:\n  plain: {hosted: http://pub.dev, version: 0.1.5}\n", "pubspec.yaml")).toEqual(["plain@0.1.5"]);
    expect(names("dependencies:\n  dotted: {hosted: https://pub.dev./, version: 0.1.5}\n", "pubspec.yaml")).toEqual(["dotted@0.1.5"]);
    const nested = "dependencies:\n  a: {x: {" + "k: v, ".repeat(700_000) + "}}\n";
    expect(() => extractPubPackages(nested, "pubspec.yaml")).not.toThrow();
  });

  it("stays cheap on an unclosed multi-line flow map", { timeout: performanceBudget(60_000) }, () => {
    const yaml = "dependencies:\n" + "  a: {\n" + "    x: y\n".repeat(200_000);
    const t0 = Date.now();
    names(yaml, "pubspec.yaml");
    expect(Date.now() - t0).toBeLessThan(performanceBudget(2000));
  });

  it("applies the hosted rules to a flow map", () => {
    const yaml = [
      "dependencies:",
      "  hijacked_pkg: {hosted: https://pub.dev, version: 0.1.5}",
      '  evil_pkg: {version: "^1.0.0"}',
      "  private_pkg: {hosted: https://pub.internal.example, version: 1.0.0}",
      "  named_private: {hosted: {name: evil_pkg, url: https://pub.internal.example}, version: 1.0.0}",
      "  named_public: {hosted: {name: other_pkg, url: https://pub.dev}, version: 2.0.0}",
    ].join("\n");
    expect(names(yaml, "pubspec.yaml")).toEqual(["hijacked_pkg@0.1.5", "evil_pkg@-", "named_public@2.0.0"]);
  });

  // pub.flutter-io.cn is the mirror the Flutter docs name for China; it
  // serves pub.dev's packages unchanged, so its lock entries are pub.dev ones.
  it("accepts lock entries resolved through the official China mirror", () => {
    const lock = LOCK.replace('url: "https://pub.dev"', 'url: "https://pub.flutter-io.cn"');
    expect(names(lock, "pubspec.lock")).toEqual(["hijacked_pkg@0.1.5", "evil_pkg@1.0.0"]);
    expect(hits(lock, "pubspec.lock").map((f) => f.match)).toContain("hijacked_pkg@0.1.5");
    // A look-alike host is not the mirror.
    const fake = LOCK.replace('url: "https://pub.dev"', 'url: "https://pub.flutter-io.cn.evil.example"');
    expect(names(fake, "pubspec.lock")).toEqual(["evil_pkg@1.0.0"]);
  });

  it("stays linear on a hostile flow map", { timeout: performanceBudget(60_000) }, () => {
    // Also a colon-free line with a long whitespace run, the shape that made
    // the old lazy-key line regex quadratic.
    const yaml = "dependencies:\n  x: {" + "{a: [b, ".repeat(100_000) + "\n  y: {" + "a,".repeat(300_000) + "}\n"
      + "  z: {" + "{a: ".repeat(100_000) + "1" + "}".repeat(100_001) + "\n"
      + "  a" + " ".repeat(200_000) + "b\n";
    const t0 = Date.now();
    extractPubPackages(yaml, "pubspec.yaml");
    expect(Date.now() - t0).toBeLessThan(performanceBudget(2000));
  });
});

describe("scanPubContent", () => {
  it("flags a hijacked version locked in pubspec.lock", () => {
    const found = hits(LOCK, "pubspec.lock");
    expect(found.map((f) => f.match).sort()).toEqual(["evil_pkg@1.0.0", "hijacked_pkg@0.1.5"]);
    const pinned = found.find((f) => f.match === "hijacked_pkg@0.1.5");
    expect(pinned?.severity).toBe("critical");
    expect(pinned?.category).toBe("malware");
    expect(pinned?.line).toBe(4);
  });

  it("does not flag a clean version or a range against a version pin", () => {
    expect(hits(LOCK.replace('version: "0.1.5"', 'version: "0.1.7"'), "pubspec.lock").map((f) => f.match)).toEqual([
      "evil_pkg@1.0.0",
    ]);
    expect(hits("dependencies:\n  hijacked_pkg: ^0.1.5\n", "pubspec.yaml")).toEqual([]);
  });

  it("leaves a clean project alone", () => {
    const yaml = "dependencies:\n  http: ^1.2.0\n  provider: 6.1.2\n";
    expect(scanPubContent(yaml, "pubspec.yaml", FEED)).toEqual([]);
  });
});
