// generate-catalog.mjs - build the publishable catalog asset and its digest.
//
// The digest is what makes integrity independent of release-asset mutability:
// it ships inside the npm package, so the anchor is the immutable npm artifact
// and the tagged git tree rather than an asset that --clobber can replace.
//
// Design: docs/threat-feed-catalog-decoupling-design.md sections 4.4 and 4.8.

import { readFileSync, writeFileSync } from "node:fs";
import { createHash } from "node:crypto";
import { gzipSync } from "node:zlib";
import { fileURLToPath } from "node:url";
import { dirname, join, resolve } from "node:path";

import { CATALOG_KEY_ORDER } from "./feed-migrate.mjs";

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), "..");

/** Read data/threat-catalog.jsonl into an array of entries. */
export function readCatalogEntries(root = repoRoot) {
  const raw = readFileSync(join(root, "data", "threat-catalog.jsonl"), "utf8");
  // Split on either ending. The file is pinned to LF in .gitattributes, but a
  // checkout that predates that pin, or a file written by another tool, would
  // otherwise leave a trailing \r inside the last JSON value on every line.
  return raw
    .split(/\r?\n/)
    .filter((l) => l.trim() !== "")
    .map((l) => JSON.parse(l));
}

/**
 * Serialize one document into its JSON, its gzip and the digest OF THE JSON.
 * Deterministic: no timestamps derived from the clock, so the same input always
 * produces the same bytes and the same digest.
 *
 * This is why the documents carry no `generatedAt`, although the design's
 * sample JSON shows one. A clock-derived field would make the output a function
 * of the day it was generated, so `check:catalog` would go red on an untouched
 * tree the next morning, exactly the failure the bundle cutoff avoids by being
 * a committed date rather than a rolling window.
 */
function serialize(doc) {
  // Hash the DECOMPRESSED JSON, not the gzip bytes: an air-gapped mirror may
  // serve an asset uncompressed and the digest must still verify. gzip output
  // is also not guaranteed byte-stable across zlib versions, which would make a
  // digest over the compressed form spuriously mismatch.
  const json = JSON.stringify(doc);
  const gz = gzipSync(Buffer.from(json, "utf-8"), { level: 9 });
  return { json, gz, sha256: createHash("sha256").update(json, "utf8").digest("hex") };
}

/** One shard holds at most this many entries. */
export const CATALOG_SHARD_MAX_ENTRIES = 50_000;

/**
 * Build the sharded catalog: an index document plus N gzipped shards.
 *
 * The chain of trust is package -> index -> shard. CATALOG_DIGEST in the
 * package is the digest of the INDEX; the index carries a digest for each
 * shard. A client installs nothing unless every link verifies, so a replaced
 * asset at any level is caught.
 */
export function buildCatalog(entries, version) {
  const shards = [];
  const shardCount = Math.max(1, Math.ceil(entries.length / CATALOG_SHARD_MAX_ENTRIES));
  for (let i = 0; i < shardCount; i++) {
    const slice = entries.slice(i * CATALOG_SHARD_MAX_ENTRIES, (i + 1) * CATALOG_SHARD_MAX_ENTRIES);
    const path = `catalog-${String(i).padStart(3, "0")}.json.gz`;
    const built = serialize({
      schema: 1,
      kind: "catalog",
      package: "supply-chain-guard",
      version,
      shard: i,
      entryCount: slice.length,
      entries: slice,
    });
    shards.push({ path, ...built, entryCount: slice.length });
  }

  const indexJson = JSON.stringify({
    schema: 1,
    kind: "catalog-index",
    package: "supply-chain-guard",
    version,
    entryCount: entries.length,
    shards: shards.map((s) => ({ path: s.path, sha256: s.sha256, entryCount: s.entryCount })),
  });

  const digest = {
    version,
    sha256: createHash("sha256").update(indexJson, "utf8").digest("hex"),
    entryCount: entries.length,
    shardCount: shards.length,
  };
  return { indexJson, shards, digest };
}

/** Render the committed TypeScript constant. Generated, never hand-edited. */
export function renderDigestModule(digest) {
  return [
    "// GENERATED by scripts/generate-catalog.mjs. Do not edit by hand.",
    "//",
    "// Shipped inside the npm package so the integrity anchor is the immutable",
    "// npm artifact and the tagged git tree, not a release asset that --clobber",
    "// can replace. sha256 is the digest of the catalog INDEX; the index carries",
    "// a digest for each shard, so the chain runs package -> index -> shard.",
    "//",
    "// A constant rather than a JSON file read at runtime because it keeps a file",
    "// read off loadThreatIntel()'s hot path, is typechecked, and supplies the",
    "// version refreshFeed() needs to build the catalog URL.",
    "export const CATALOG_DIGEST = {",
    `  version: ${JSON.stringify(digest.version)},`,
    `  sha256: ${JSON.stringify(digest.sha256)},`,
    `  entryCount: ${digest.entryCount},`,
    `  shardCount: ${digest.shardCount},`,
    "} as const;",
    "",
  ].join("\n");
}

// Structural only. This file is PUBLIC, so it deliberately contains no list of
// the organization's own hostnames or repository names: embedding one would
// publish exactly what the check exists to keep unpublished. A 10.x address or
// a .internal host is recognizable without knowing whose it is.
//
// An earlier draft also required a source naming a public vendor from a list.
// Measured against the shipped feed, that would have failed 514 of 20,969
// entries, 465 of them carrying no source at all. A check that judges a value
// has to enumerate spellings and the next spelling walks past, so this one
// checks shape and structure only.
const PRIVATE_SHAPES = [
  /(?:^|[^\d.])10\.\d{1,3}\.\d{1,3}\.\d{1,3}(?![\d.])/,
  /(?:^|[^\d.])192\.168\.\d{1,3}\.\d{1,3}(?![\d.])/,
  /(?:^|[^\d.])172\.(?:1[6-9]|2\d|3[01])\.\d{1,3}\.\d{1,3}(?![\d.])/,
  /(?:^|[^\d.])127\.\d{1,3}\.\d{1,3}\.\d{1,3}(?![\d.])/,
  /(?:^|[^\d.])169\.254\.\d{1,3}\.\d{1,3}(?![\d.])/,
  /(?:^|[.@/\s])(?:localhost|[\w-]+\.(?:local|internal|lan|corp|home))(?:[:/\s]|$)/i,
  /[A-Za-z]:[\\/](?:Users|Windows|Program)/i,
  /(?:^|\s)\/(?:home|Users|root|srv|opt)\//,
];

/**
 * The fields a catalog entry may carry.
 *
 * Imported from the migration rather than mirrored, because a second hand-kept
 * copy of a key list is exactly the pair that silently diverges: the plan's
 * draft of this file listed eleven keys, including the legacy `note` and
 * `ecosystem` that Phase 1 had already removed from FEED_ENTRY_KEYS. Sharing
 * one definition means `note` is rejected here as an unknown key without any
 * separate rule needing to remember it.
 */
export const FEED_ENTRY_KEYS = new Set(CATALOG_KEY_ORDER);

/**
 * Refuse to publish a catalog carrying anything that is not public advisory
 * data. Reports LINE NUMBERS, never the offending value, so a violation cannot
 * leak through the error message either.
 */
export function checkCatalogHygiene(entries) {
  const violations = [];
  entries.forEach((entry, i) => {
    const line = i + 1;
    for (const key of Object.keys(entry)) {
      if (!FEED_ENTRY_KEYS.has(key)) {
        violations.push(`line ${line}: key "${key}" is not an allowed FeedIOC field`);
      }
    }
    for (const field of ["value", "source"]) {
      const v = entry[field];
      if (typeof v === "string" && PRIVATE_SHAPES.some((re) => re.test(v))) {
        violations.push(`line ${line}: ${field} matches a private-infrastructure shape`);
      }
    }
  });
  return violations;
}

// The client's per-document decompression limit, mirrored from src/feed.ts.
// This is a compatibility FLOOR, not a tunable: released clients carry their
// own copy, so raising it here would not help a single existing install. The
// drift test asserts the two stay equal.
export const CATALOG_MAX_DECOMPRESSED_BYTES = 64 * 1024 * 1024;

// A shard must stay well under the floor. At 50,000 entries and the measured
// 165 serialized bytes per entry a shard is about 8.25 MB, so this sits four
// times above anything the generator can currently produce. It exists so a
// future change to the entry shape cannot quietly inflate a shard past what
// old clients can read.
export const CATALOG_SHARD_MAX_BYTES = 32 * 1024 * 1024;

export function checkCatalogSize(shards) {
  const violations = [];
  for (const shard of shards) {
    const bytes = Buffer.byteLength(shard.json, "utf8");
    if (bytes <= CATALOG_SHARD_MAX_BYTES) continue;
    violations.push(
      `shard ${shard.path} is ${bytes} bytes, over the ${CATALOG_SHARD_MAX_BYTES} byte ` +
        `per-shard budget (${((bytes / CATALOG_MAX_DECOMPRESSED_BYTES) * 100).toFixed(0)} percent ` +
        `of the ${CATALOG_MAX_DECOMPRESSED_BYTES} byte client decompression limit). ` +
        `Lower CATALOG_SHARD_MAX_ENTRIES; do NOT raise the client limit, because ` +
        `released clients carry the old value and cannot be reached.`,
    );
  }
  return violations;
}

/** Print at most 25 violations, then say how many were withheld. */
function reportViolations(violations) {
  for (const v of violations.slice(0, 25)) console.error(`  ${v}`);
  if (violations.length > 25) {
    console.error(`  ... and ${violations.length - 25} more`);
  }
}

const invokedDirectly =
  process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url);

if (invokedDirectly) {
  const version = JSON.parse(readFileSync(join(repoRoot, "package.json"), "utf8")).version;
  const entries = readCatalogEntries();
  const { indexJson, shards, digest } = buildCatalog(entries, version);
  const modulePath = join(repoRoot, "src", "catalog-digest.ts");
  const rendered = renderDigestModule(digest);

  // Hygiene and size are checked BEFORE anything is written or compared, so a
  // run that refuses never leaves a half-written asset behind and never reports
  // "up to date" about a catalog it would have refused to publish.
  const violations = [...checkCatalogHygiene(entries), ...checkCatalogSize(shards)];
  if (violations.length > 0) {
    console.error(
      `\n  data/threat-catalog.jsonl has ${violations.length} violation(s) and will not be published:\n`,
    );
    reportViolations(violations);
    console.error("");
    process.exit(1);
  }

  if (process.argv.includes("--check")) {
    // Compare with CR stripped on both sides. src/catalog-digest.ts is pinned to
    // LF in .gitattributes, but a Windows checkout with core.autocrlf=true still
    // materializes CRLF for any file that pin does not cover, and an exact !==
    // would then report a freshly generated file as stale.
    const onDisk = readFileSync(modulePath, "utf8").replace(/\r/g, "");
    if (onDisk !== rendered.replace(/\r/g, "")) {
      console.error("src/catalog-digest.ts is stale; run `npm run catalog:generate` and commit it.");
      process.exit(1);
    }
    console.log(`catalog digest up to date (${digest.entryCount} entries, v${digest.version}).`);
  } else {
    writeFileSync(join(repoRoot, "catalog-index.json"), indexJson);
    for (const shard of shards) writeFileSync(join(repoRoot, shard.path), shard.gz);
    writeFileSync(modulePath, rendered);
    console.log(
      `catalog:generate OK - ${digest.entryCount} entries in ${digest.shardCount} shard(s), ` +
        `index sha256 ${digest.sha256.slice(0, 12)}...`,
    );
  }
}
