// GENERATED by scripts/generate-catalog.mjs. Do not edit by hand.
//
// Shipped inside the npm package so the integrity anchor is the immutable
// npm artifact and the tagged git tree, not a release asset that --clobber
// can replace. sha256 is the digest of the catalog INDEX; the index carries
// a digest for each shard, so the download chain runs package -> index ->
// shard. entriesSha256 pins the canonical entries array after installation,
// so a self-consistent replacement cache is refused on the next process run.
//
// A constant rather than a JSON file read at runtime because it keeps a file
// read off loadThreatIntel()'s hot path, is typechecked, and supplies the
// version refreshFeed() needs to build the catalog URL.
export const CATALOG_DIGEST = {
  version: "6.4.1",
  sha256: "d6b7394431b3a79e6a42d72ac56ed4973ed9d18faa2c7600370964803059ddc5",
  entriesSha256: "03bf81738d2f33995feeb5f8707ee3b2cd8f4d058241dc0f88c61c64eea4cf34",
  entryCount: 92821,
  shardCount: 2,
} as const;
