// GENERATED by scripts/generate-catalog.mjs. Do not edit by hand.
//
// Shipped inside the npm package so the integrity anchor is the immutable
// npm artifact and the tagged git tree, not a release asset that --clobber
// can replace. sha256 is the digest of the catalog INDEX; the index carries
// a digest for each shard, so the download chain runs package -> index ->
// shard. entriesSha256 pins the canonical entries array after installation,
// so a self-consistent replacement cache is refused on the next process run.
//
// A constant rather than a JSON file read at runtime because it keeps a file
// read off loadThreatIntel()'s hot path, is typechecked, and supplies the
// version refreshFeed() needs to build the catalog URL.
export const CATALOG_DIGEST = {
  version: "6.5.1",
  sha256: "2d13faeef4af30ea066ad754f4f25879cba747b98cddb4a7e47fc580f56e8e57",
  entriesSha256: "fcfe40fff917d00e3b86b7d453335518f64c5b511d89cc8d9b952e8a98b7ec3f",
  entryCount: 263732,
  shardCount: 6,
} as const;
