// GENERATED by scripts/generate-catalog.mjs. Do not edit by hand.
//
// Shipped inside the npm package so the integrity anchor is the immutable
// npm artifact and the tagged git tree, not a release asset that --clobber
// can replace. sha256 is the digest of the catalog INDEX; the index carries
// a digest for each shard, so the download chain runs package -> index ->
// shard. entriesSha256 pins the canonical entries array after installation,
// so a self-consistent replacement cache is refused on the next process run.
//
// A constant rather than a JSON file read at runtime because it keeps a file
// read off loadThreatIntel()'s hot path, is typechecked, and supplies the
// version refreshFeed() needs to build the catalog URL.
export const CATALOG_DIGEST = {
  version: "6.2.4",
  sha256: "0bd7faf5e8b24b6c9aae0901f3ec11b4263444014d98c37856b7b8bd7fa05039",
  entriesSha256: "30bec8cfa2f31fd2f05b4016c8e513531a13e7c668cf746a97198cdab05c592a",
  entryCount: 81884,
  shardCount: 2,
} as const;
