/**
 * Security Operations Center (SOC) exporter (v4.6).
 *
 * Exports scan results in formats consumable by SIEM, ticketing,
 * and incident management systems.
 */

import type { ScanReport, Finding, IncidentCluster, Remediation } from "./types.js";

/**
 * Export as JSON incident bundle for SIEM ingestion.
 */
export function exportIncidentBundle(report: ScanReport): string {
  const partialScan = report.partialScan === true;
  const bundle = {
    schema: "supply-chain-guard-incident/1.0",
    scannerVersion: report.tool,
    timestamp: report.timestamp,
    target: report.target,
    scanType: report.scanType,
    ...(partialScan ? { partialScan: true } : {}),
    riskScore: report.score,
    // A clean risk level is not a valid verdict when coverage was incomplete.
    riskLevel: partialScan && report.riskLevel === "clean" ? "unknown" : report.riskLevel,
    confidence: report.riskDimensions?.confidence ?? null,
    summary: {
      totalFindings: report.findings.length,
      critical: report.summary.critical,
      high: report.summary.high,
      medium: report.summary.medium,
      low: report.summary.low,
      suppressedCount: report.suppressedCount ?? 0,
    },
    incidents: (report.incidents ?? []).map((i) => ({
      id: i.id,
      name: i.name,
      severity: i.severity,
      confidence: i.confidence,
      narrative: i.narrative,
      indicators: i.indicators,
      findingCount: i.findings.length,
    })),
    findings: report.findings.map((f) => ({
      rule: f.rule,
      severity: f.severity,
      confidence: f.confidence ?? null,
      category: f.category ?? null,
      description: f.description,
      file: f.file ?? null,
      line: f.line ?? null,
      correlationId: f.correlationId ?? null,
    })),
    remediations: report.remediations ?? [],
    riskDimensions: report.riskDimensions ?? null,
    trustBreakdown: report.trustBreakdown ?? null,
  };

  return JSON.stringify(bundle, null, 2);
}

/**
 * Export as markdown incident report for tickets/issues.
 */
export function exportIncidentMarkdown(report: ScanReport): string {
  const lines: string[] = [];
  const partialScan = report.partialScan === true;
  const riskLabel = partialScan
    ? report.riskLevel === "clean"
      ? "UNKNOWN; PARTIAL SCAN"
      : `${report.riskLevel.toUpperCase()}; PARTIAL SCAN`
    : report.riskLevel.toUpperCase();

  lines.push("# Supply Chain Security Incident Report");
  lines.push("");
  lines.push(`**Target:** ${report.target}`);
  lines.push(`**Scan Time:** ${report.timestamp}`);
  lines.push(`**Risk Score:** ${report.score}/100 (${riskLabel})`);
  if (partialScan) {
    lines.push("");
    lines.push("> [!WARNING]");
    lines.push(
      "> **Scan incomplete:** Coverage was partial. Findings and the observed score reflect only the content that could be analyzed; this is not a clean verdict.",
    );
  }
  lines.push("");

  // Incidents
  if (report.incidents && report.incidents.length > 0) {
    lines.push("## Detected Incidents");
    lines.push("");
    for (const incident of report.incidents) {
      lines.push(`### ${incident.severity.toUpperCase()}: ${incident.name}`);
      lines.push(`**Confidence:** ${Math.round(incident.confidence * 100)}%`);
      lines.push("");
      lines.push(incident.narrative);
      lines.push("");
      lines.push(`**Indicators:** ${incident.indicators.join(", ")}`);
      lines.push("");
    }
  }

  // Critical findings
  const critical = report.findings.filter((f) => f.severity === "critical");
  if (critical.length > 0) {
    lines.push("## Critical Findings");
    lines.push("");
    for (const f of critical) {
      lines.push(`- **${f.rule}**: ${f.description}`);
      if (f.file) lines.push(`  - File: \`${f.file}${f.line ? `:${f.line}` : ""}\``);
    }
    lines.push("");
  }

  // Remediations
  if (report.remediations && report.remediations.length > 0) {
    lines.push("## Recommended Actions");
    lines.push("");
    for (const rem of report.remediations) {
      lines.push(`### ${rem.priority.toUpperCase()}: ${rem.title}`);
      lines.push(rem.description);
      lines.push("");
      for (const step of rem.steps) {
        lines.push(`1. ${step}`);
      }
      lines.push("");
    }
  }

  // Playbooks
  if (report.playbooks && report.playbooks.length > 0) {
    lines.push("## Response Playbooks");
    lines.push("");
    for (const pb of report.playbooks) {
      lines.push(`### ${pb.incidentType}`);
      lines.push(pb.summary);
      lines.push("");
      lines.push("**Immediate Actions:**");
      for (const a of pb.immediateActions) lines.push(`- ${a}`);
      lines.push("");
      lines.push("**Investigation:**");
      for (const s of pb.investigationSteps) lines.push(`- ${s}`);
      lines.push("");
    }
  }

  lines.push("---");
  lines.push(`*Generated by ${report.tool}*`);

  return lines.join("\n");
}

/**
 * Export as CSV summary for executive reporting.
 */
export function exportCsvSummary(report: ScanReport): string {
  const status = report.partialScan === true ? "partial" : "complete";
  const partialScan = report.partialScan === true ? "true" : "false";
  const csvCell = (value: unknown): string =>
    `"${String(value ?? "").replace(/"/g, '""')}"`;
  const lines = [
    "rule,severity,confidence,file,description,scan_status,partial_scan",
  ];

  // Preserve coverage status even when there are no findings. An empty partial
  // scan must never be indistinguishable from a completed clean scan.
  if (report.findings.length === 0) {
    lines.push(
      ["", "", "", "", "", status, partialScan].map(csvCell).join(","),
    );
  }

  for (const f of report.findings) {
    lines.push(
      [
        f.rule,
        f.severity,
        f.confidence,
        f.file,
        f.description,
        status,
        partialScan,
      ]
        .map(csvCell)
        .join(","),
    );
  }
  return lines.join("\n");
}
